-- ** Database generated with pgModeler (PostgreSQL Database Modeler).
-- ** pgModeler version: 1.2.2
-- ** PostgreSQL version: 17.0
-- ** Project Site: pgmodeler.io
-- ** Model Author: ---
-- ** Tablespaces creation must be performed outside a multi lined SQL file. 
-- ** These commands were put in this file only as a convenience.

-- object: tabletesat | type: TABLESPACE --
-- DROP TABLESPACE IF EXISTS tabletesat...
CREATE TAB...


-- ** Database creation must be performed outside a multi lined SQL file. 
-- ** These commands were put in this file only as a convenience.

-- object: gamedatabase | type: DATABASE --
-- DROP DATABASE IF EXISTS gamedat...
CREATE DATABASE game...

SET search_path TO pg_catalog,public;
-- ddl-end --

-- object: public."gameTables" | type: TABLE --
-- DROP TABLE IF EXISTS public."game...
CREATE TABLE public."gameTables" (
	"gameID" integer NOT NULL GENERAT...
	"PlayerCount" inte...
	"Pentagram" ...
	CO...
-- object: public."playerInstance" | type: TABLE --
-- DROP TABLE IF EXISTS public."playerInsta...
CREATE TABLE public."playerInstance" (
	"instanceID" integer NOT NULL GENERA...
	"gameID_gameTables" in...
	"PlayerName" tex...
	"DeckName" text...
	"Win" boolean ...
	"...
-- object: "gameTables_fk" | type: CONSTRAINT --
-- ALTER TABLE public."playerInstance" DROP CONSTRAINT IF EXIST...
AL...

